module.exports =  {
    INVALID_CREDENTIAL          : 'INVALID_CREDENTIAL',
    ACCOUNT_LOCK                : 'ACCOUNT_LOCK',
    FAILED_ADD_NEW_USER         : 'FAILED_ADD_NEW_USER',
    FAILED_ADD_NEW_STAFF        : 'FAILED_ADD_NEW_STAFF',
    TEMPORARY_PASSWORD_EXPIRED  : 'TEMPORARY_PASSWORD_EXPIRED',
    INVALID_EMAIL_ADDRESS       : 'INVALID_EMAIL_ADDRESS',
    INVALID_PASSWORD            : 'INVALID_PASSWORD',
    REQUIRED_FIRSTNAME          : 'REQUIRED_FIRST_NAME',
    REQUIRED_LASTNAME           : 'REQUIRED_LAST_NAME',
    INVALID_CONTACT_NUMBER      : 'INVALID_CONTACT_NUMBER',
    NO_VALID_CODE               : 'NO_VALID_CODE',
//CLINIC
    CLINIC_TYPE_NOT_FOUND       : 'CLINIC_TYPE_NOT_FOUND',
    CLINIC_TYPE_NOT_CREATED     : 'CLINIC_TYPE_NOT_CREATED',
    GET_ALL_CLINIC_TYPE_ERROR   : 'GET_ALL_CLINIC_TYPE_ERROR',
    FAILED_ADD_NEW_CLINIC_TYPE  : 'FAILED_ADD_NEW_CLINIC_TYPE'
}
