module.exports =  {
    INVALID_CREDENTIAL          : 'INVALID_CREDENTIAL',
    ACCOUNT_LOCK                : 'ACCOUNT_LOCK',
    FAILED_ADD_NEW_USER         : 'FAILED_ADD_NEW_USER',
    FAILED_ADD_NEW_STAFF        : 'FAILED_ADD_NEW_STAFF',
    TEMPORARY_PASSWORD_EXPIRED  : 'TEMPORARY_PASSWORD_EXPIRED',
    INVALID_EMAIL_ADDRESS       : 'INVALID_EMAIL_ADDRESS',
    INVALID_PASSWORD            : 'INVALID_PASSWORD',
    REQUIRED_FIRSTNAME          : 'REQUIRED_FIRSTNAME',
    REQUIRED_LASTNAME           : 'REQUIRED_LASTNAME',
    REQUIRED_MOBILENUMBER       : 'REQUIRED_MOBILENUMBER',
    INVALID_CONTACTNUMBER       : 'INVALID_CONTACTNUMBER',
    NO_VALID_CODE               : 'NO_VALID_CODE',

}
