module.exports =  {
    INVALID_CREDENTIAL          : 'INVALID_CREDENTIAL',
    ACCOUNT_LOCK                : 'ACCOUNT_LOCK',
    FAILED_ADD_NEW_USER         : 'FAILED_ADD_NEW_USER',
    FAILED_ADD_NEW_STAFF        : 'FAILED_ADD_NEW_STAFF',
    TEMPORARY_PASSWORD_EXPIRED  : "TEMPORARY_PASSWORD_EXPIRED"
}
